### ISSUE TITLE
Add text overlay for hotspots

### ISSUE THREAD

**Issue by kavyasukumar** [kavyasukumar/playablechart#1]
![2c1afc56-101a-11e5-9a2e-4c294968fa35](https://cloud.githubusercontent.com/assets/5184932/8111253/c6586d58-102e-11e5-92ce-a13383f786dc.png)

**Comment by kavyasukumar** [comment]
Colors
Main backround & Whites: #f9f9f9
Light blue: #c7eef2
Orange pop: #f6901e
Text: #4c4d4e ($default-text-color)

**Comment by frnsys** [comment]
closed via #4
